### ISSUE TITLE
Freeze after clicking "Play the Game!"

### ISSUE THREAD

**Issue by ApolloZhu** [Trojan89878/Everest-Game#1]
I've seen several infinite loops like in [reduceO](https://github.com/TroyNeubauer/Everest-Game/blob/master/Everest%20Game%201.0%20alpha.py#L94)(which is [called directly in gameLoop](https://github.com/TroyNeubauer/Everest-Game/blob/master/Everest%20Game%201.0%20alpha.py#L227)) and [intro](https://github.com/TroyNeubauer/Everest-Game/blob/master/Everest%20Game%201.0%20alpha.py#L179)(which seems that won't escape unless quit the app)
Does this program work on your computer?

**Comment by TroyNeubauer** [comment]
Looking back on that project I am not suprised at all that there are infinite loops. When I made that game, I had been working in python for a long time, however I didn't program very often and all of my previous experience been done using very little functions/ bad practices. You can see this a lot with the getHeight() function, the if statements wouldn't be neccsarry if I used >= and <= instead of > and <. At the time I didn't know how to debug code and figure out what was wrong. That was the first time I had created a non text based program. I didn't know how to do much of anything. I'm unsure if the version on GitHub even works! Tommorow I will check it out and if I finish my biology project, I might improve it.

**Comment by ApolloZhu** [comment]
Can you use separate branches for python and java? If possible, make me a collaborator so you don't have to take care of the python branch often

**Comment by TroyNeubauer** [comment]
I was unfamiliar with branches and git so I did some research and created a new "Python" branch. I also added you as a collaborator. After some thought, because I haven't used Python since I made this game a year ago, I decided that version 2 will be made in stock Java with Java's graphics API.

**Comment by ApolloZhu** [comment]
Thanks
